-optimizations   code/simplification/arithmetic,!code/simplification/cast,!field/*,! class/merging/*,!method/inlining/*
-optimizationpasses 5
-allowaccessmodification
-dontskipnonpubliclibraryclasses
-dontpreverify
-repackageclasses ''
